export const villages = [
  {
    id: "haflong",
    name: "Haflong",
    shortName: "Haflong",
    riskLevel: "moderate",
    riskScore: 48,
    rainfall24h: 42,
    rainfall7d: 186,
    slopeAngle: 31,
    roadStatus: "Open",
    roadName: "NH-27 approach",
    updated: "08:42 AM",
    coordinates: { x: 46, y: 49 },
    explanation: "Rainfall is approaching the 50 mm safe threshold. Monitor hillside drainage around the town approach.",
  },
  {
    id: "maibong",
    name: "Maibong",
    shortName: "Maibong",
    riskLevel: "high",
    riskScore: 72,
    rainfall24h: 68,
    rainfall7d: 284,
    slopeAngle: 38,
    roadStatus: "Restricted",
    roadName: "NH-27, Maibong bend",
    updated: "08:36 AM",
    coordinates: { x: 22, y: 37 },
    explanation: "Rainfall 68 mm in 24 hours exceeds the safe threshold of 50 mm for this slope gradient.",
  },
  {
    id: "jatinga",
    name: "Jatinga",
    shortName: "Jatinga",
    riskLevel: "severe",
    riskScore: 91,
    rainfall24h: 94,
    rainfall7d: 412,
    slopeAngle: 44,
    roadStatus: "Blocked",
    roadName: "Jatinga–Haflong Road",
    updated: "08:18 AM",
    coordinates: { x: 60, y: 27 },
    explanation: "Saturated soil and a steep 44° slope create a severe movement risk. Road access is blocked.",
  },
  {
    id: "mahurbond",
    name: "Mahur Bond",
    shortName: "Mahur Bond",
    riskLevel: "high",
    riskScore: 76,
    rainfall24h: 74,
    rainfall7d: 301,
    slopeAngle: 36,
    roadStatus: "Restricted",
    roadName: "Mahur–Silchar Road",
    updated: "08:29 AM",
    coordinates: { x: 73, y: 47 },
    explanation: "Heavy rainfall has raised soil moisture on a steep hillside. Travel only for essential movement.",
  },
  {
    id: "umrangso",
    name: "Umrangso",
    shortName: "Umrangso",
    riskLevel: "low",
    riskScore: 22,
    rainfall24h: 18,
    rainfall7d: 96,
    slopeAngle: 22,
    roadStatus: "Open",
    roadName: "Umrangso town road",
    updated: "08:51 AM",
    coordinates: { x: 28, y: 68 },
    explanation: "Rainfall and ground movement indicators remain within normal range for this area.",
  },
  {
    id: "diyungbra",
    name: "Diyungbra",
    shortName: "Diyungbra",
    riskLevel: "moderate",
    riskScore: 53,
    rainfall24h: 49,
    rainfall7d: 214,
    slopeAngle: 29,
    roadStatus: "Open",
    roadName: "Diyungbra village road",
    updated: "08:47 AM",
    coordinates: { x: 52, y: 73 },
    explanation: "Ground moisture is elevated after several wet days. Local teams are monitoring the village road.",
  },
  {
    id: "new-pangsha",
    name: "New Pangsha",
    shortName: "New Pangsha",
    riskLevel: "low",
    riskScore: 17,
    rainfall24h: 12,
    rainfall7d: 81,
    slopeAngle: 19,
    roadStatus: "Open",
    roadName: "Pangsha link road",
    updated: "08:55 AM",
    coordinates: { x: 80, y: 74 },
    explanation: "No unusual rainfall or slope movement has been detected in the latest update.",
  },
];

export const rainfallTrend = [
  { day: "18 Jun", rainfall: 22 },
  { day: "19 Jun", rainfall: 38 },
  { day: "20 Jun", rainfall: 27 },
  { day: "21 Jun", rainfall: 56 },
  { day: "22 Jun", rainfall: 44 },
  { day: "23 Jun", rainfall: 73 },
  { day: "Today", rainfall: 68 },
];

export const alerts = [
  {
    id: "alert-1",
    village: "Jatinga",
    riskLevel: "severe",
    roadName: "Jatinga–Haflong Road",
    message: "Severe landslide risk due to saturated slopes. Avoid the Jatinga–Haflong Road until further notice.",
    timestamp: "Today, 08:20 AM",
    channels: ["App", "SMS"],
  },
  {
    id: "alert-2",
    village: "Mahur Bond",
    riskLevel: "high",
    roadName: "Mahur–Silchar Road",
    message: "High landslide risk in Mahur Bond due to heavy rainfall. Travel only for essential movement.",
    timestamp: "Today, 07:55 AM",
    channels: ["App", "SMS"],
  },
  {
    id: "alert-3",
    village: "Maibong",
    riskLevel: "high",
    roadName: "NH-27, Maibong bend",
    message: "Heavy rainfall has increased landslide risk near Maibong. Drive slowly and follow local advisories.",
    timestamp: "Yesterday, 06:40 PM",
    channels: ["App"],
  },
  {
    id: "alert-4",
    village: "Haflong",
    riskLevel: "moderate",
    roadName: "NH-27 approach",
    message: "Moderate risk watch is active for Haflong. Report cracks, falling rocks, or slope movement.",
    timestamp: "Yesterday, 03:15 PM",
    channels: ["SMS"],
  },
];

export const reports = [
  { id: "RPT-2401", village: "Jatinga", type: "Crack in road", timestamp: "Today, 08:04 AM", status: "Pending Review" },
  { id: "RPT-2398", village: "Mahur Bond", type: "Slope movement", timestamp: "Yesterday, 06:22 PM", status: "Verified" },
  { id: "RPT-2394", village: "Maibong", type: "Blocked road", timestamp: "Yesterday, 01:48 PM", status: "Verified" },
  { id: "RPT-2389", village: "Haflong", type: "Other", timestamp: "18 Jun, 11:12 AM", status: "Pending Review" },
];

export const riskMeta = {
  low: { label: "Low", color: "#27856a", soft: "#e5f4ef", dot: "bg-emerald-500" },
  moderate: { label: "Moderate", color: "#c58a1d", soft: "#fff5d9", dot: "bg-amber-400" },
  high: { label: "High", color: "#d56b26", soft: "#fff0e6", dot: "bg-orange-500" },
  severe: { label: "Severe", color: "#c5484d", soft: "#fce8e8", dot: "bg-red-500" },
};
